class SettingList:

	DEFAULT_CHECKBOX_STATES = {
			"tm_all": False,
			"tm_balance": False,
			"tm_noload": False,
			"vol_all": False,
			"vol_rms": False,
			"vol_fund": False,
			"vol_thd": False,
			"vol_freq": False,
			"vol_residual": False,
			"vol_sliding": False,
			"curr_all": False,
			"curr_rms": False,
			"curr_fund": False,
			"curr_demand": False,
			"curr_thd": False,
			"curr_tdd": False,
			"curr_cf": False,
			"curr_kf": False,
			"curr_residual": False,
			"pow_all": False,
			"pow_p": False,
			"pow_q": False,
			"pow_s": False,
			"pow_pf": False,
			"pow_demand": False,
			"pow_energy": False,
			"anal_all": False,
			"anal_phasor": False,
			"anal_harmonics": False,
			"anal_waveform": False,
			"anal_volt_sym": False,
			"anal_volt_unbal": False,
			"anal_curr_sym": False,
			"anal_curr_unbal": False,
			"sys_all": False,
			"m_s_initialize": False,
			"m_s_vol": False,
			"m_s_curr": False,
			"m_s_demand": False,
			"m_s_power": False,
			"m_s_dip": False,
			"m_s_pq_curve": False,
			"m_s_swell": False,
			"m_s_volt_conn": False,
			"m_s_ethernet": False,
			"m_s_rs485": False,
			"m_s_advanced": False,
			"m_s_data_reset": False,
			"m_s_demadn_sync": False,
			"m_s_test_mode": False,
			"m_s_description": False,
			"m_s_locale": False,
			"m_s_local_time": False,
			"m_s_summer_time": False,
			"m_s_ntp": False,
			"m_s_led": False,
			"m_s_lcd_buzzer": False,
			"m_s_cb": False,
			}
	
	CHECKBOX_MAPPING = [
		('tm_all', 'cb_tm_all'), #0
		('tm_balance', 'cb_tm_balance'),
		('tm_noload', 'cb_tm_noload'),
		('vol_all', 'cb_vol_all'),
		('vol_rms', 'cb_vol_rms'),
		('vol_fund', 'cb_vol_fund'),
		('vol_thd', 'cb_vol_thd'),
		('vol_freq', 'cb_vol_freq'),
		('vol_residual', 'cb_vol_residual'),
		('vol_sliding', 'cb_vol_sliding'),
		('curr_all', 'cb_curr_all'), #10
		('curr_rms', 'cb_curr_rms'),
		('curr_fund', 'cb_curr_fund'),
		('curr_demand', 'cb_curr_demand'),
		('curr_thd', 'cb_curr_thd'),
		('curr_tdd', 'cb_curr_tdd'),
		('curr_cf', 'cb_curr_cf'),
		('curr_kf', 'cb_curr_kf'),
		('curr_residual', 'cb_curr_residual'),
		('pow_all', 'cb_pow_all'), #19
		('pow_p', 'cb_pow_p'),
		('pow_q', 'cb_pow_q'),
		('pow_s', 'cb_pow_s'),
		('pow_pf', 'cb_pow_pf'),
		('pow_demand', 'cb_pow_demand'),
		('pow_energy', 'cb_pow_energy'),
		('anal_all', 'cb_anal_all'), #26
		('anal_phasor', 'cb_anal_phasor'),
		('anal_harmonics', 'cb_anal_harmonics'),
		('anal_waveform', 'cb_anal_waveform'),
		('anal_volt_sym', 'cb_anal_volt_sym'),
		('anal_volt_unbal', 'cb_anal_volt_unbal'),
		('anal_curr_sym', 'cb_anal_curr_sym'),
		('anal_curr_unbal', 'cb_anal_curr_unbal'),
		('sys_all', 'cb_sys_all'), #34
		('m_s_initialize', 'cb_m_s_initialize'),
		('m_s_meas_all', 'cb_m_s_meas_all'), #36
		('m_s_vol', 'cb_m_s_vol'),
		('m_s_curr', 'cb_m_s_curr'),
		('m_s_demand', 'cb_m_s_demand'),
		('m_s_power', 'cb_m_s_power'),
		('m_s_event_all', 'cb_m_s_event_all'), #41
		('m_s_dip', 'cb_m_s_dip'),
		('m_s_swell', 'cb_m_s_swell'),
		('m_s_pq_curve', 'cb_m_s_pq_curve'),
		('m_s_volt_conn', 'cb_m_s_volt_conn'),
		('m_s_network_all', 'cb_m_s_network_all'), #46
		('m_s_ethernet', 'cb_m_s_ethernet'),
		('m_s_rs485', 'cb_m_s_rs485'),
		('m_s_advanced', 'cb_m_s_advanced'),
		('m_s_control_all', 'cb_m_s_control_all'), #50
		('m_s_data_reset', 'cb_m_s_data_reset'),
		('m_s_demand_sync', 'cb_m_s_demand_sync'),
		('m_s_test_mode', 'cb_m_s_test_mode'),
		('m_s_system_all', 'cb_m_s_system_all'),#54
		('m_s_description', 'cb_m_s_description'),
		('m_s_locale', 'cb_m_s_locale'),
		('m_s_local_time', 'cb_m_s_local_time'),
		('m_s_summer_time', 'cb_m_s_summer_time'),
		('m_s_ntp', 'cb_m_s_ntp'),
		('m_s_led', 'cb_m_s_led'),
		('m_s_lcd_buzzer', 'cb_m_s_lcd_buzzer'),
		('m_s_cb', 'cb_m_s_cb'), #63
		]
	
	DASHBORAD_TEST = [
		('vol_all', 'demo_mea_vol_all'), #0
		('vol_rms', 'demo_mea_vol_rms'),
		('vol_fund', 'demo_mea_vol_fund'),
		('vol_thd', 'demo_mea_vol_thd'),
		('vol_freq', 'demo_mea_vol_freq'),
		('vol_residual', 'demo_mea_vol_residual'),
		('vol_sliding', 'demo_mea_vol_sliding'),
		('curr_all', 'demo_mea_curr_all'),
        ('curr_rms', 'demo_mea_curr_rms'),
        ('curr_fund', 'demo_mea_curr_fund'),
        ('curr_demand', 'demo_mea_curr_demand'),
        ('curr_thd', 'demo_mea_curr_thd'),
        ('curr_tdd', 'demo_mea_curr_tdd'),
        ('curr_cf', 'demo_mea_curr_cf'),
        ('curr_kf', 'demo_mea_curr_kf'),
        ('curr_residual', 'demo_mea_curr_residual'),
		('pow_all', 'demo_mea_pow_all'),
        ('pow_p', 'demo_mea_pow_active'),
        ('pow_q', 'demo_mea_pow_reactive'),
        ('pow_s', 'demo_mea_pow_apparent'),
        ('pow_pf', 'demo_mea_pow_pf'),
        ('pow_demand', 'demo_mea_pow_demand'),
        ('pow_energy', 'demo_mea_pow_energy'),
        ('anal_all', 'demo_mea_anal_all'),
        ('anal_phasor', 'demo_mea_anal_phasor'),
        ('anal_harmonics', 'demo_mea_anal_harmonics'),
        ('anal_waveform', 'demo_mea_anal_waveform'),
        ('anal_volt_sym', 'demo_mea_anal_voltsym'),
        ('anal_volt_unbal', 'demo_mea_anal_voltunbal'),
        ('anal_curr_sym', 'demo_mea_anal_cursym'),
        ('anal_curr_unbal', 'demo_mea_anal_currunbal'), #30
		('m_s_vol', 'setup_meter_s_m_vol'),
		('m_s_curr', 'setup_meter_s_m_curr')
		]